# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.CharField(max_length=200)),
                ('awarded_by', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AdministrativeResponsibilitie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('start_month', models.CharField(max_length=50)),
                ('start_year', models.IntegerField()),
                ('end_month', models.CharField(max_length=50)),
                ('end_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.CharField(help_text='Enter names of all participants separated by commas', max_length=200)),
                ('topic', models.CharField(max_length=1000)),
                ('event', models.CharField(help_text='Enter name of event and place where hosted', max_length=200)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(help_text='eg. MA101', max_length=5)),
                ('semester', models.CharField(choices=[('odd', 'July-Nov'), ('even', 'Jan-March')], max_length=4)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('bsbe', 'Biosciences and Bioengineering'), ('chem', 'Chemistry'), ('ce', 'Chemical Engineering'), ('cive', 'Civil Engineering'), ('des', 'Design'), ('cse', 'Computer Science and Engineering'), ('eee', 'Electrical and Electronics Engineering'), ('ece', 'Electrical and Communication Engineering'), ('hss', 'Humanities and Social Sciences'), ('phy', 'Physics'), ('math', 'Mathematics'), ('mech', 'Mechanical Engineering')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('asso', 'Associate Professor'), ('asst', 'Assistant Professor'), ('prof', 'Professor'), ('visf', 'Visiting Professor'), ('hono', 'Honorary Professor')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('bt', 'B.Tech'), ('bs', 'B.Sc'), ('be', 'B.E'), ('mt', 'M.Tech'), ('ms', 'M.Sc'), ('ph', 'PhD')], help_text='Degree obtained', max_length=2)),
                ('branch', models.CharField(help_text='Enter full name of the Discipline', max_length=50)),
                ('institute', models.CharField(help_text='Enter full name of the Institute', max_length=50)),
                ('duration', models.CharField(help_text='Please use the following format: <em>XXXX-XX</em>', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter First name', max_length=20)),
                ('last_name', models.CharField(help_text='Enter Last name', max_length=20)),
                ('phone_res', models.CharField(default='+91-361-258XXXX', help_text='Please use the following format: <em>+91-361-258XXXX</em>.', max_length=15)),
                ('phone_office', models.CharField(default='+91-361-258XXXX', help_text='Please use the following format: <em>+91-361-258XXXX</em>.', max_length=15)),
                ('iitg_email', models.EmailField(default='@iitg.ernet.in', help_text='Please use the following format: <em>username@iitg.ernet.in</em>.', max_length=254)),
                ('other_email', models.EmailField(help_text='Please use the following format: <em>username@company.com</em>.', max_length=254)),
                ('room_number', models.CharField(help_text='Please use the following format: X-XXX', max_length=5)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Department')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Designation')),
            ],
            options={
                'ordering': ['-last_name'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter title of Journal', max_length=100)),
                ('contributors', models.CharField(help_text='Enter names of all contributors', max_length=100)),
                ('book', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('institute', models.CharField(max_length=200)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.CharField(help_text='Enter your interests separated by commas', max_length=200)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Faculty')),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Faculty'),
        ),
        migrations.AddField(
            model_name='conference',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Faculty'),
        ),
        migrations.AddField(
            model_name='administrativeresponsibilitie',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Faculty'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Faculty'),
        ),
    ]
