# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile Picture', null=True, upload_to='profile_pic'),
        ),
    ]
