# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_department_dept_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_pic',
            field=models.ImageField(blank=True, help_text='Department Picture', null=True, upload_to='media/dept_pic'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile Picture', null=True, upload_to='media/profile_pic'),
        ),
    ]
