# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_faculty_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='phone_office',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='phone_res',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='photo',
        ),
        migrations.AddField(
            model_name='faculty',
            name='office_phone',
            field=models.CharField(default='+91-361-258XXXX', max_length=15),
        ),
        migrations.AddField(
            model_name='faculty',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='media/profile_pic'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='residential_phone',
            field=models.CharField(blank=True, default='+91-361-258XXXX', max_length=15),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='homepage.Department'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='homepage.Designation'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='iitg_email',
            field=models.EmailField(default='@iitg.ernet.in', max_length=254, verbose_name='IITG Webmail'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='other_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Secondary Email'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='room_number',
            field=models.CharField(default='H-000', max_length=5),
        ),
    ]
