# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20171116_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('topic', models.CharField(max_length=75)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='AdministrativeResponsibilitie',
            new_name='AdministrativeResponsibility',
        ),
        migrations.AlterModelOptions(
            name='administrativeresponsibility',
            options={'verbose_name_plural': 'AdministrativeResponsibility'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Faculties'},
        ),
        migrations.AddField(
            model_name='faculty',
            name='bio',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Faculty'),
        ),
    ]
