# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20171117_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('odd', 'July-Nov'), ('even', 'Jan-April')], max_length=4),
        ),
    ]
