# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20171117_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['year'], 'verbose_name_plural': 'Courses'},
        ),
    ]
