# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20171117_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_logo',
            field=models.ImageField(blank=True, help_text='Department Logo', null=True, upload_to='media/dept_logo'),
        ),
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.CharField(choices=[('bt', 'B.Tech'), ('bs', 'B.Sc'), ('be', 'B.E'), ('mt', 'M.Tech'), ('ms', 'M.Sc'), ('ph', 'PhD')], max_length=2, null=True),
        ),
    ]
