# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20171117_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='block',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.EmailField(default='@iitg.ernet.in', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='phone',
            field=models.CharField(default='+91-361-258XXXX', max_length=15, null=True),
        ),
    ]
