# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_auto_20171117_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('sponsor', models.CharField(max_length=50, null=True)),
                ('budget', models.CharField(max_length=20, null=True)),
                ('duration', models.CharField(default='20XX-XX', max_length=7, null=True)),
                ('role', models.CharField(max_length=30, null=True)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Faculty')),
            ],
        ),
    ]
