# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_auto_20171117_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='bio',
            new_name='biography',
        ),
    ]
