# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 21:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_auto_20171118_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='end_year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='student',
            name='start_year',
            field=models.IntegerField(default=2016),
        ),
    ]
