# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_auto_20171119_0313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['id'], 'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterField(
            model_name='education',
            name='branch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('bt', 'Bachelor of Technology (B.Tech)'), ('bs', 'Bachelor of Science (B.Sc)'), ('be', 'Bachelor of Engineering (B.E.)'), ('mt', 'Master of Technology (M.Tech)'), ('ms', 'Master of Science (M.Sc)'), ('ph', 'Doctor of Philosophy (Ph.D.')], max_length=2),
        ),
        migrations.AlterField(
            model_name='education',
            name='duration',
            field=models.CharField(default='XXXX-XX', max_length=7),
        ),
        migrations.AlterField(
            model_name='education',
            name='institute',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='iitg_email',
            field=models.EmailField(default='username@iitg.ernet.in', max_length=254, verbose_name='Primary Email'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='interests',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='other_email',
            field=models.EmailField(blank=True, default='username@gmail.com', max_length=254, verbose_name='Secondary Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(choices=[('bt', 'B.Tech'), ('bs', 'B.Sc'), ('be', 'B.E.'), ('mt', 'M.Tech'), ('ms', 'M.Sc'), ('ph', 'Ph.D.')], max_length=2, null=True),
        ),
    ]
