# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_auto_20171119_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/profile_pic/default_profile_pic.jpg', upload_to='media/profile_pic'),
        ),
    ]
