# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_auto_20171129_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Department'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Designation'),
        ),
    ]
